namespace ChurchAssetTracker.Models;

public class PersonRow { public int PersonId { get; set; } public string FullName { get; set; } = ""; public string? Phone { get; set; } public string? Email { get; set; } public string? MinistryTeam { get; set; } public bool IsActive { get; set; } }
public class AssetRow { public int AssetId { get; set; } public string AssetName { get; set; } = ""; public string? PhotoPath { get; set; } public string? Category { get; set; } public string? AssetTag { get; set; } public string? SerialNumber { get; set; } public string? CurrentCondition { get; set; } public int TotalQuantity { get; set; } public int QuantityCheckedOut { get; set; } public int QuantityAvailable { get; set; } public bool IsActive { get; set; } }
public class KeyRow { public int KeyId { get; set; } public string KeyCode { get; set; } = ""; public string KeyName { get; set; } = ""; public bool IsMasterKey { get; set; } public bool IsActive { get; set; } public string? AccessAreas { get; set; } }
public class CheckoutRow { public int CheckoutId { get; set; } public string AssetName { get; set; } = ""; public string Borrower { get; set; } = ""; public int QuantityOut { get; set; } public DateTime CheckoutDate { get; set; } public DateTime? ExpectedReturnDate { get; set; } public DateTime? ActualReturnDate { get; set; } public string Status { get; set; } = ""; }
public class KeyAssignmentRow { public int KeyAssignmentId { get; set; } public string KeyName { get; set; } = ""; public string KeyCode { get; set; } = ""; public string KeyHolder { get; set; } = ""; public DateTime IssuedDate { get; set; } public DateTime? ReturnedDate { get; set; } public string Status { get; set; } = ""; }

public class AuditLogRow { public int AuditLogId { get; set; } public string ActionType { get; set; } = ""; public string EntityType { get; set; } = ""; public int? EntityId { get; set; } public string? Description { get; set; } public DateTime CreatedDate { get; set; } public string? UserDisplayName { get; set; } }
